# Generated by Django 4.2.6 on 2023-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(default='Rabat', max_length=64),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(default='CFK', max_length=3),
        ),
    ]
